### ISSUE TITLE
Critical | Magento commerce 2.4.4 | Facebook Business Extension compatibility issue

### ISSUE THREAD

**Issue by nitishcorra** [facebookincubator/facebook-for-magento2#124]
### Contact Details

nsuthar@corra.com

### What happened?

We have purchased/downloaded an extension from the Magento market place https://marketplace.magento.com/facebook-facebook-for-magento2.html.

After the Magento commerce upgrade to 2.4.4, we are facing a PHP8.1 compatibility issue with the latest extension version 1.4.4 and due to this it is not working with Magento commerce 2.4.4

We are getting the below error in the PHP log on every page in the front.

Please try to provide a solution for this issue ASAP.

We are assuming this could be an issue with the php-business-sdk library, as it is using old version 9. x instead of 14. May this will help.

Please let us know if you need any other details.

Nitish

### Magento Version

2.4.4

### Plugin Version

1.4.5

### Relevant log output

```shell
#0 /vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/UserData.php(34): Magento\Framework\App\ErrorHandler->handler(8192, 'Return type of ...', '/Applications/M...', 535)
#1 /vendor/composer/ClassLoader.php(571): include('/Applications/M...')
#2 /vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Applications/M...')
#3 /vendor/facebook/facebook-for-magento2/Helper/ServerEventFactory.php(28): Composer\Autoload\ClassLoader->loadClass('FacebookAds\\Obj...')
#4 /vendor/facebook/facebook-for-magento2/Helper/ServerEventFactory.php(167): Facebook\BusinessExtension\Helper\ServerEventFactory::newEvent('ViewContent', '52ddc800-0a06-4...')
#5 /vendor/facebook/facebook-for-magento2/Observer/ViewContent.php(73): Facebook\BusinessExtension\Helper\ServerEventFactory::createEvent('ViewContent', Array, '52ddc800-0a06-4...')
#6 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Facebook\BusinessExtension\Observer\ViewContent->execute(Object(Magento\Framework\Event\Observer))
#7 /vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Facebook\BusinessExtension\Observer\ViewContent), Object(Magento\Framework\Event\Observer))
#8 /vendor/magento/module-staging/Model/Event/Manager.php(97): Magento\Framework\Event\Invoker\InvokerDefault->dispatch(Array, Object(Magento\Framework\Event\Observer))
#9 /generated/code/Magento/Staging/Model/Event/Manager/Proxy.php(95): Magento\Staging\Model\Event\Manager->dispatch('facebook_busine...', Array)
#10 /vendor/facebook/facebook-for-magento2/Block/Pixel/Common.php(152): Magento\Staging\Model\Event\Manager\Proxy->dispatch('facebook_busine...', Array)
#11 /vendor/facebook/facebook-for-magento2/view/frontend/templates/pixel/view_content.phtml(5): Facebook\BusinessExtension\Block\Pixel\Common->trackServerEvent('52ddc800-0a06-4...')
#12 /vendor/magento/framework/View/TemplateEngine/Php.php(71): include('/Applications/M...')
#13 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php->render(Object(Facebook\BusinessExtension\Block\Pixel\ViewContent), '/Applications/M...', Array)
#14 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callParent('render', Array)
#15 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor->Magento\Framework\Interception\{closure}(Object(Facebook\BusinessExtension\Block\Pixel\ViewContent), '/Applications/M...', Array)
#16 /generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor->___callPlugins('render', Array, Array)
#17 /vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor->render(Object(Facebook\BusinessExtension\Block\Pixel\ViewContent), '/Applications/M...', Array)
#18 /vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template->fetchView('/Applications/M...')
#19 /vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template->_toHtml()
#20 /vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock->Magento\Framework\View\Element\{closure}()
#21 /vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock->_loadCache()
#22 /vendor/magento/framework/View/Layout.php(578): Magento\Framework\View\Element\AbstractBlock->toHtml()
#23 /vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout->_renderBlock('fbe.pixel.view_...')
#24 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('fbe.pixel.view_...')
#25 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('fbe.pixel.view_...', false)
#26 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('before.body.end', false)
#27 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('before.body.end')
#28 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('before.body.end', false)
#29 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('page.wrapper', false)
#30 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('page.wrapper')
#31 /vendor/magento/framework/View/Layout.php(606): Magento\Framework\View\Layout->renderElement('page.wrapper', false)
#32 /vendor/magento/framework/View/Layout.php(557): Magento\Framework\View\Layout->_renderContainer('root', false)
#33 /vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout->renderNonCachedElement('root')
#34 /vendor/magento/framework/View/Layout.php(975): Magento\Framework\View\Layout->renderElement('root')
#35 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Layout->getOutput()
#36 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Layout\Interceptor->___callParent('getOutput', Array)
#37 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Layout\Interceptor->Magento\Framework\Interception\{closure}()
#38 /generated/code/Magento/Framework/View/Layout/Interceptor.php(50): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#39 /vendor/magento/framework/View/Result/Page.php(260): Magento\Framework\View\Layout\Interceptor->getOutput()
#40 /vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page->render(Object(Magento\Framework\App\Response\Http\Interceptor))
#41 /vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#42 /vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor->___callParent('renderResult', Array)
#43 /vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor->Magento\Framework\Interception\{closure}(Object(Magento\Framework\App\Response\Http\Interceptor))
#44 /generated/code/Magento/Framework/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Page\Interceptor->___callPlugins('renderResult', Array, Array)
#45 /vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor->renderResult(Object(Magento\Framework\App\Response\Http\Interceptor))
#46 /vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http->launch()
#47 /pub/index.php(30): Magento\Framework\App\Bootstrap->run(Object(Magento\Framework\App\Http\Interceptor))
#48 {main} in /vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/UserData.php on line 34
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by dankocrama980** [comment]
Same Here still not update

**Comment by alexwatever** [comment]
We're seeing this issue as well.

**Comment by hakamshop** [comment]
same here

**Comment by gfrey-namcopool** [comment]
any updates?

**Comment by AngelReev** [comment]
it seems they don't care about the support of the extension

**Comment by konstanchuk** [comment]
[https://github.com/konstanchuk/magento2-facebook-php8](https://github.com/konstanchuk/magento2-facebook-php8) - this solution works for us.

**Comment by ecrocombe** [comment]
Workaround provided in #131
