### ISSUE TITLE
[Bug]: Magento Frontend Not loading after installing the version 1.4.5

### ISSUE THREAD

**Issue by pratikvs** [facebookincubator/facebook-for-magento2#127]
### Contact Details

pratik.sonawadekar@borngroup.com

### What happened?

Hi ,
I am using Magento2.4.5 and 2.4.5-p1 versions . I installed this module in both the magento versions and tried loading the frontend home page. The frontend home page is blank. I checked the error by viewing the page source it gives me the below error. I tried downgrading the Plugin version to 1.4.5 to 1.4.4 but still we are facing the same issue.

`
<b>Fatal error</b>:  During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of FacebookAds\Object\ServerSide\AdsPixelSettings::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/magento/releases/4/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/AdsPixelSettings.php on line 154 in /var/www/magento/releases/4/vendor/magento/framework/App/ErrorHandler.php:62
--
  | Stack trace:
  | #0 /var/www/magento/releases/4/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/AdsPixelSettings.php(33): Magento\Framework\App\ErrorHandler-&gt;handler()
  | #1 /var/www/magento/releases/4/vendor/composer/ClassLoader.php(571): include('...')
  | #2 /var/www/magento/releases/4/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
  | #3 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/Helper/FBEHelper.php(563): Composer\Autoload\ClassLoader-&gt;loadClass()
  | #4 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/Helper/AAMFieldsExtractorHelper.php(51): Facebook\BusinessExtension\Helper\FBEHelper-&gt;getAAMSettings()
  | #5 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/Block/Pixel/Head.php(52): Facebook\BusinessExtension\Helper\AAMFieldsExtractorHelper-&gt;getNormalizedUserData()
  | #6 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/view/frontend/templates/pixel/head.phtml(20): Facebook\BusinessExtension\Block\Pixel\Head-&gt;getPixelInitCode()
  | #7 /var/www/magento/releases/4/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
  | #8 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php-&gt;render()
  | #9 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callParent()
  | #10 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;Magento\Framework\Interception\{closure}()
  | #11 /var/www/magento/releases/4/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callPlugins()
  | #12 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;render()
  | #13 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template-&gt;fetchView()
  | #14 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template-&gt;_toHtml()
  | #15 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock-&gt;Magento\Framework\View\Element\{closure}()
  | #16 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock-&gt;_loadCache()
  | #17 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock-&gt;toHtml()
  | #18 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;___callParent()
  | #19 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;Magento\Framework\Interception\{closure}()
  | #20 /var/www/magento/releases/4/generated/code/Facebook/BusinessExtension/Block/Pixel/Head/Interceptor.php(23): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;___callPlugins()
  | #21 /var/www/magento/releases/4/vendor/magento/framework/View/Layout.php(578): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;toHtml()
  | #22 /var/www/magento/releases/4/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout-&gt;_renderBlock()
  | #23 /var/www/magento/releases/4/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout-&gt;renderNonCachedElement()
  | #24 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout-&gt;renderElement()
  | #25 /var/www/magento/releases/4/vendor/magento/module-theme/view/frontend/templates/html/container.phtml(7): Magento\Framework\View\Element\AbstractBlock-&gt;getChildHtml()
  | #26 /var/www/magento/releases/4/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
  | #27 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php-&gt;render()
  | #28 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callParent()
  | #29 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;Magento\Framework\Interception\{closure}()
  | #30 /var/www/magento/releases/4/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callPlugins()
  | #31 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;render()
  | #32 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template-&gt;fetchView()
  | #33 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template-&gt;_toHtml()
  | #34 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock-&gt;Magento\Framework\View\Element\{closure}()
  | #35 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock-&gt;_loadCache()
  | #36 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock-&gt;toHtml()
  | #37 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Element\Template\Interceptor-&gt;___callParent()
  | #38 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Element\Template\Interceptor-&gt;Magento\Framework\Interception\{closure}()
  | #39 /var/www/magento/releases/4/generated/code/Magento/Framework/View/Element/Template/Interceptor.php(23): Magento\Framework\View\Element\Template\Interceptor-&gt;___callPlugins()
  | #40 /var/www/magento/releases/4/vendor/magento/framework/View/Result/Page.php(253): Magento\Framework\View\Element\Template\Interceptor-&gt;toHtml()
  | #41 /var/www/magento/releases/4/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page-&gt;render()
  | #42 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout-&gt;renderResult()
  | #43 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor-&gt;___callParent()
  | #44 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor-&gt;Magento\Framework\Interception\{closure}()
  | #45 /var/www/magento/releases/4/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Page\Interceptor-&gt;___callPlugins()
  | #46 /var/www/magento/releases/4/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor-&gt;renderResult()
  | #47 /var/www/magento/releases/4/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http-&gt;launch()
  | #48 /var/www/magento/releases/4/pub/index.php(30): Magento\Framework\App\Bootstrap-&gt;run()
  | #49 {main} in <b>/var/www/magento/releases/4/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/AdsPixelSettings.php</b> on line <b>33</b><br />
`
Requesting to check and update the issue.

### Magento Version

2.4.5, 2.4.5-p1

### Plugin Version

1.4.5, 1.4.4, 1.4.2

### Relevant log output

```shell
<b>Fatal error</b>:  During inheritance of ArrayAccess: Uncaught Exception: Deprecated Functionality: Return type of FacebookAds\Object\ServerSide\AdsPixelSettings::offsetExists($offset) should either be compatible with ArrayAccess::offsetExists(mixed $offset): bool, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in /var/www/magento/releases/4/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/AdsPixelSettings.php on line 154 in /var/www/magento/releases/4/vendor/magento/framework/App/ErrorHandler.php:62
Stack trace:
#0 /var/www/magento/releases/4/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/AdsPixelSettings.php(33): Magento\Framework\App\ErrorHandler-&gt;handler()
#1 /var/www/magento/releases/4/vendor/composer/ClassLoader.php(571): include('...')
#2 /var/www/magento/releases/4/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile()
#3 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/Helper/FBEHelper.php(563): Composer\Autoload\ClassLoader-&gt;loadClass()
#4 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/Helper/AAMFieldsExtractorHelper.php(51): Facebook\BusinessExtension\Helper\FBEHelper-&gt;getAAMSettings()
#5 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/Block/Pixel/Head.php(52): Facebook\BusinessExtension\Helper\AAMFieldsExtractorHelper-&gt;getNormalizedUserData()
#6 /var/www/magento/releases/4/vendor/facebook/facebook-for-magento2/view/frontend/templates/pixel/head.phtml(20): Facebook\BusinessExtension\Block\Pixel\Head-&gt;getPixelInitCode()
#7 /var/www/magento/releases/4/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#8 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php-&gt;render()
#9 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callParent()
#10 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;Magento\Framework\Interception\{closure}()
#11 /var/www/magento/releases/4/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callPlugins()
#12 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;render()
#13 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template-&gt;fetchView()
#14 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template-&gt;_toHtml()
#15 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock-&gt;Magento\Framework\View\Element\{closure}()
#16 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock-&gt;_loadCache()
#17 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock-&gt;toHtml()
#18 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;___callParent()
#19 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;Magento\Framework\Interception\{closure}()
#20 /var/www/magento/releases/4/generated/code/Facebook/BusinessExtension/Block/Pixel/Head/Interceptor.php(23): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;___callPlugins()
#21 /var/www/magento/releases/4/vendor/magento/framework/View/Layout.php(578): Facebook\BusinessExtension\Block\Pixel\Head\Interceptor-&gt;toHtml()
#22 /var/www/magento/releases/4/vendor/magento/framework/View/Layout.php(555): Magento\Framework\View\Layout-&gt;_renderBlock()
#23 /var/www/magento/releases/4/vendor/magento/framework/View/Layout.php(510): Magento\Framework\View\Layout-&gt;renderNonCachedElement()
#24 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(511): Magento\Framework\View\Layout-&gt;renderElement()
#25 /var/www/magento/releases/4/vendor/magento/module-theme/view/frontend/templates/html/container.phtml(7): Magento\Framework\View\Element\AbstractBlock-&gt;getChildHtml()
#26 /var/www/magento/releases/4/vendor/magento/framework/View/TemplateEngine/Php.php(71): include('...')
#27 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\TemplateEngine\Php-&gt;render()
#28 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callParent()
#29 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;Magento\Framework\Interception\{closure}()
#30 /var/www/magento/releases/4/generated/code/Magento/Framework/View/TemplateEngine/Php/Interceptor.php(23): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;___callPlugins()
#31 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(263): Magento\Framework\View\TemplateEngine\Php\Interceptor-&gt;render()
#32 /var/www/magento/releases/4/vendor/magento/framework/View/Element/Template.php(293): Magento\Framework\View\Element\Template-&gt;fetchView()
#33 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1095): Magento\Framework\View\Element\Template-&gt;_toHtml()
#34 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(1099): Magento\Framework\View\Element\AbstractBlock-&gt;Magento\Framework\View\Element\{closure}()
#35 /var/www/magento/releases/4/vendor/magento/framework/View/Element/AbstractBlock.php(660): Magento\Framework\View\Element\AbstractBlock-&gt;_loadCache()
#36 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Element\AbstractBlock-&gt;toHtml()
#37 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Element\Template\Interceptor-&gt;___callParent()
#38 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Element\Template\Interceptor-&gt;Magento\Framework\Interception\{closure}()
#39 /var/www/magento/releases/4/generated/code/Magento/Framework/View/Element/Template/Interceptor.php(23): Magento\Framework\View\Element\Template\Interceptor-&gt;___callPlugins()
#40 /var/www/magento/releases/4/vendor/magento/framework/View/Result/Page.php(253): Magento\Framework\View\Element\Template\Interceptor-&gt;toHtml()
#41 /var/www/magento/releases/4/vendor/magento/framework/View/Result/Layout.php(171): Magento\Framework\View\Result\Page-&gt;render()
#42 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\View\Result\Layout-&gt;renderResult()
#43 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\View\Result\Page\Interceptor-&gt;___callParent()
#44 /var/www/magento/releases/4/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\View\Result\Page\Interceptor-&gt;Magento\Framework\Interception\{closure}()
#45 /var/www/magento/releases/4/generated/code/Magento/Framework/View/Result/Page/Interceptor.php(32): Magento\Framework\View\Result\Page\Interceptor-&gt;___callPlugins()
#46 /var/www/magento/releases/4/vendor/magento/framework/App/Http.php(120): Magento\Framework\View\Result\Page\Interceptor-&gt;renderResult()
#47 /var/www/magento/releases/4/vendor/magento/framework/App/Bootstrap.php(264): Magento\Framework\App\Http-&gt;launch()
#48 /var/www/magento/releases/4/pub/index.php(30): Magento\Framework\App\Bootstrap-&gt;run()
#49 {main} in <b>/var/www/magento/releases/4/vendor/facebook/php-business-sdk/src/FacebookAds/Object/ServerSide/AdsPixelSettings.php</b> on line <b>33</b><br />
```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ecrocombe** [comment]
Workaround provided in #131
