### ISSUE TITLE
 Error saving product

### ISSUE THREAD

**Issue by chags** [facebookincubator/facebook-for-magento2#38]
The module creates several fields in the product registration. But it doesn't allow you to make any changes and save. Check the error below.

`Error: Call to undefined method Facebook\BusinessExtension\Model\System\Config::getOutOfStockThreshold() in /var/www/html/magento2/app/code/Facebook/BusinessExtension/Model/Product/Feed/Builder/Inventory.php:126 Stack trace: #0 /var/www/html/magento2/app/code/Facebook/BusinessExtension/Model/Product/Feed/Builder.php(362): Facebook\BusinessExtension\Model\Product\Feed\Builder\Inventory->getAvailability() #1 /var/www/html/magento2/app/code/Facebook/BusinessExtension/Model/Product/Feed/Method/BatchApi.php(69): Facebook\BusinessExtension\Model\Product\Feed\Builder->buildProductEntry() #2 /var/www/html/magento2/app/code/Facebook/BusinessExtension/Observer/ProcessProductAfterSaveEventObserver.php(57): Facebook\BusinessExtension\Model\Product\Feed\Method\BatchApi->buildProductRequest() #3 /var/www/html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Facebook\BusinessExtension\Observer\ProcessProductAfterSaveEventObserver->execute() #4 /var/www/html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() #5 /var/www/html/magento2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch() #6 /var/www/html/magento2/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch() #7 /var/www/html/magento2/vendor/magento/framework/Model/AbstractModel.php(829): Magento\Framework\Event\Manager\Proxy->dispatch() #8 /var/www/html/magento2/vendor/magento/module-catalog/Model/Product.php(974): Magento\Framework\Model\AbstractModel->afterSave() #9 /var/www/html/magento2/generated/code/Magento/Catalog/Model/Product/Interceptor.php(349): Magento\Catalog\Model\Product->afterSave() #10 /var/www/html/magento2/vendor/magento/framework/EntityManager/Observer/AfterEntitySave.php(34): Magento\Catalog\Model\Product\Interceptor->afterSave() #11 /var/www/html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Magento\Framework\EntityManager\Observer\AfterEntitySave->execute() #12 /var/www/html/magento2/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod() #13 /var/www/html/magento2/vendor/magento/framework/Event/Manager.php(66): Magento\Framework\Event\Invoker\InvokerDefault->dispatch() #14 /var/www/html/magento2/generated/code/Magento/Framework/Event/Manager/Proxy.php(95): Magento\Framework\Event\Manager->dispatch() #15 /var/www/html/magento2/vendor/magento/framework/EntityManager/EventManager.php(51): Magento\Framework\Event\Manager\Proxy->dispatch() #16 /var/www/html/magento2/vendor/magento/framework/EntityManager/Operation/Update.php(110): Magento\Framework\EntityManager\EventManager->dispatchEntityEvent() #17 /var/www/html/magento2/vendor/magento/framework/EntityManager/EntityManager.php(96): Magento\Framework\EntityManager\Operation\Update->execute() #18 /var/www/html/magento2/vendor/magento/module-catalog/Model/ResourceModel/Product.php(758): Magento\Framework\EntityManager\EntityManager->save() #19 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Model\ResourceModel\Product->save() #20 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callParent() #21 /var/www/html/magento2/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(58): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() #22 /var/www/html/magento2/vendor/magento/module-catalog-search/Model/Indexer/Fulltext/Plugin/Product.php(28): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->addCommitCallback() #23 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\CatalogSearch\Model\Indexer\Fulltext\Plugin\Product->aroundSave() #24 /var/www/html/magento2/vendor/magento/framework/App/Cache/FlushCacheByTags.php(69): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() #25 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Cache\FlushCacheByTags->aroundSave() #26 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Model\ResourceModel\Product\Interceptor->Magento\Framework\Interception\{closure}() #27 /var/www/html/magento2/generated/code/Magento/Catalog/Model/ResourceModel/Product/Interceptor.php(273): Magento\Catalog\Model\ResourceModel\Product\Interceptor->___callPlugins() #28 /var/www/html/magento2/vendor/magento/framework/Model/AbstractModel.php(655): Magento\Catalog\Model\ResourceModel\Product\Interceptor->save() #29 /var/www/html/magento2/generated/code/Magento/Catalog/Model/Product/Interceptor.php(2442): Magento\Framework\Model\AbstractModel->save() #30 /var/www/html/magento2/vendor/magento/module-catalog/Controller/Adminhtml/Product/Save.php(142): Magento\Catalog\Model\Product\Interceptor->save() #31 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Catalog\Controller\Adminhtml\Product\Save->execute() #32 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent() #33 /var/www/html/magento2/vendor/magento/framework/App/Action/Plugin/ActionFlagNoDispatchPlugin.php(51): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() #34 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Framework\App\Action\Plugin\ActionFlagNoDispatchPlugin->aroundExecute() #35 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() #36 /var/www/html/magento2/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(26): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins() #37 /var/www/html/magento2/vendor/magento/framework/App/Action/Action.php(111): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->execute() #38 /var/www/html/magento2/vendor/magento/module-backend/App/AbstractAction.php(151): Magento\Framework\App\Action\Action->dispatch() #39 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Backend\App\AbstractAction->dispatch() #40 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callParent() #41 /var/www/html/magento2/app/code/WeltPixel/Backend/Plugin/Utility.php(76): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() #42 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): WeltPixel\Backend\Plugin\Utility->aroundDispatch() #43 /var/www/html/magento2/vendor/magento/module-backend/App/Action/Plugin/Authentication.php(143): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() #44 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(135): Magento\Backend\App\Action\Plugin\Authentication->aroundDispatch() #45 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->Magento\Framework\Interception\{closure}() #46 /var/www/html/magento2/generated/code/Magento/Catalog/Controller/Adminhtml/Product/Save/Interceptor.php(39): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->___callPlugins() #47 /var/www/html/magento2/vendor/magento/framework/App/FrontController.php(186): Magento\Catalog\Controller\Adminhtml\Product\Save\Interceptor->dispatch() #48 /var/www/html/magento2/vendor/magento/framework/App/FrontController.php(118): Magento\Framework\App\FrontController->processRequest() #49 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(58): Magento\Framework\App\FrontController->dispatch() #50 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(138): Magento\Framework\App\FrontController\Interceptor->___callParent() #51 /var/www/html/magento2/vendor/magento/framework/Interception/Interceptor.php(153): Magento\Framework\App\FrontController\Interceptor->Magento\Framework\Interception\{closure}() #52 /var/www/html/magento2/generated/code/Magento/Framework/App/FrontController/Interceptor.php(26): Magento\Framework\App\FrontController\Interceptor->___callPlugins() #53 /var/www/html/magento2/vendor/magento/framework/App/Http.php(116): Magento\Framework\App\FrontController\Interceptor->dispatch() #54 /var/www/html/magento2/generated/code/Magento/Framework/App/Http/Interceptor.php(24): Magento\Framework\App\Http->launch() #55 /var/www/html/magento2/vendor/magento/framework/App/Bootstrap.php(263): Magento\Framework\App\Http\Interceptor->launch() #56 /var/www/html/magento2/index.php(39): Magento\Framework\App\Bootstrap->run() #57 {main}
Fatal error: Uncaught Exception: User Error: Some transactions have not been committed or rolled back in /var/www/html/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php on line 4020 in /var/www/html/magento2/vendor/magento/framework/App/ErrorHandler.php:61 Stack trace: #0 [internal function]: Magento\Framework\App\ErrorHandler->handler() #1 /var/www/html/magento2/vendor/magento/framework/DB/Adapter/Pdo/Mysql.php(4020): trigger_error() #2 [internal function]: Magento\Framework\DB\Adapter\Pdo\Mysql->__destruct() #3 {main} thrown in /var/www/html/magento2/vendor/magento/framework/App/ErrorHandler.php on line 61`

**Comment by chags** [comment]
see video: https://www.loom.com/share/52b2b8412a2245f2b8bbfc26a5c7fb3c
