### ISSUE TITLE
Getting an exception after installation 

### ISSUE THREAD

**Issue by MoeezQadri** [facebookincubator/facebook-for-magento2#41]
Fatal error: Uncaught Error: Call to undefined method FacebookAds\Object\ServerSide\Event::setActionSource() in /var/www/html/app/code/Facebook/BusinessExtension/Helper/ServerEventFactory.php:38 Stack trace: #0 /var/www/html/app/code/Facebook/BusinessExtension/Helper/ServerEventFactory.php(167): Facebook\BusinessExtension\Helper\ServerEventFactory::newEvent('ViewCategory', '761cf8a7-9e28-4...') #1 /var/www/html/app/code/Facebook/BusinessExtension/Observer/ViewCategory.php(51): Facebook\BusinessExtension\Helper\ServerEventFactory::createEvent('ViewCategory', Array, '761cf8a7-9e28-4...') #2 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(88): Facebook\BusinessExtension\Observer\ViewCategory->execute(Object(Magento\Framework\Event\Observer)) #3 /var/www/html/vendor/magento/framework/Event/Invoker/InvokerDefault.php(74): Magento\Framework\Event\Invoker\InvokerDefault->_callObserverMethod(Object(Facebook\BusinessExtension\Observer\ViewCategory), Object(Magento\Framework\Event\Observer)) #4 /var/www/html in /var/www/html/app/code/Facebook/BusinessExtension/Helper/ServerEventFactory.php on line 38

**Comment by MoeezQadri** [comment]
The issue seems to be with the view content event -when i view the category or a product page, please advise what we should do?

**Comment by mariano66ecommerce** [comment]
Please, downgrade composer Facebook Business SDK to version 8.0.0
