### ISSUE TITLE
Page is not working 500 internal server error

### ISSUE THREAD

**Issue by sumeetmagento** [facebookincubator/facebook-for-magento2#48]
There is no error in Magento logs so when we check on server logs then got his error - 

`AH01071: Got error 'PHP message: PHP Fatal error: Uncaught Error: Call to undefined method Facebook\\BusinessExtension\\Model\\System\\Config::getOutOfStockThreshold() in /var/www/vhosts/xyx/httpdocs/app/code/Facebook/BusinessExtension/Model/Product/Feed/Builder/Inventory.php:126\nStack trace:\n#0 /var/www/vhosts/xyz/httpdocs/app/code/Facebook/BusinessExtension/Model/Product/Feed/Builder.php(362): Facebook\\BusinessExtension\\Model\\Product\\Feed\\Builder\\Inventory->getAvailability()\n#1 /var/www/vhosts/xyz/httpdocs/app/code/Facebook/BusinessExtension/Model/Product/Feed/Method/BatchApi.php(69): Facebook\\BusinessExtension\\Model\\Product\\Feed\\Builder->buildProductEntry(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#2 /var/www/vhosts/xyz/httpdocs/app/code/Facebook/BusinessExtension/Observer/ProcessProductAfterSaveEventObserver.php(57): Facebook\\BusinessExtension\\Model\\Product\\Feed\\Method\\BatchApi->buildProductRequest(Object(Magento\\Catalog\\Model\\Product\\Interceptor))\n#3 /var/www/vhosts/m...', referer: https://xyz/admin_xyz/catalog/product/edit/id/22106/key/fccd6d61dda1f3fd1da63fa8c668c2b3a84f37d2bc1a090c195f8bd2b8903a1b/`

**Comment by naumansigma** [comment]
Install it using Composer it has dependency on php-business-sdk.

**Comment by sumeetmagento** [comment]
@naumansigma 
thanks for your reply but this issue is coming when we download this extension from magento market place and when we download this extension from git then it is working fine.

**Comment by aziwaan** [comment]
Hi @sumeetmagento, Im facing this error just now after trying to uninstall this extension.  Have you any links to uninstall steps.  Ive removed the extension, removed the SDK composer package, removed the Facebook table in the DB, Upgraded the DB, Compiled DI, Indexed and Cleared caches but Im still getting the error when loading the products list in the backend.

**Comment by ayoubmcw** [comment]
Hi @sumeetmagento did you fix the  error plz hep ??
